import Head from "next/head";
import styles from "../styles/Home.module.css";
import { PageLayoutTypes, Site } from "./types";

import { fetchPageProps } from "../core/page/page-fetcher";

import PageRenderer from "../components/renderers/PageRenderer/PageRenderer";

type SlugLandingPageProps = {
  site: Site;
  pageLayout: PageLayoutTypes;
};

const SlugLandingPage = ({ pageLayout, site }: SlugLandingPageProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{site.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageRenderer pageLayout={pageLayout} site={site} />
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const { params } = context;
  const pageProps = await fetchPageProps(params);

  console.log("PAGE PROPS: ", pageProps);

  return {
    props: {
      ...pageProps,
    },
  };
}

export default SlugLandingPage;
