import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Page } from "./types";

import PageRenderer from "../packages/app/renderers/PageRenderer/PageRenderer";

type HomeProps = {
  title: string;
  page: Page;
};

const Home = ({ title, page }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <p>hello header</p>
      </header>

      <main className={styles.main}>
        <PageRenderer page={page} />
      </main>

      <footer className={styles.footer}>
        <p>Hello Footer</p>
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  return {
    props: {
      id: "test",
      title: "My App Title",
      page: {
        id: "pageRendererID",
        type: "page",
        fields: {
          id: "componentsRendererID",
          type: "banner",
          title: "Main Page",
        },
      },
    },
  };
};

export default Home;
